name: 'example-cron-action'
on:
  schedule:
    - cron: '0 */6 * * *' # At every 6th hour

jobs:
  retryTesterCwdDeploy:
    env:
      PROD_EXTENSION_ID: 'nfadnflafdfmekapgcgddbccooagpndk' # Chrome production page id
      CLIENT_ID: '990187593175-iurgn499pfh1urue4smreg0ato5fftee.apps.googleusercontent.com'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Remove scheduled job after 10 attempts
        uses: cardinalby/unschedule-job-action@v1
        if: github.run_number > 10
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} # SHA that triggered your original job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v1
        with:
          node-version: 15.4
      - run: npm ci
      - run: npm run build-prod
      - name: Chrome Addon Action
        continue-on-error: true
        # You may pin to the exact commit or the version.
        # uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7
        uses: trmcnvn/chrome-addon@v2
        with:
          # ID of the extension that you are updating
          extension: ${{env.PROD_EXTENSION_ID}} # optional
          # Path to a .zip of your addon
          zip: dist/threadhelper.zip # optional
          # Google OAuth2 client id
          client-id: ${{env.CLIENT_ID}} # optional
          # Google OAuth2 client secret
          client-secret: ${{secrets.CWS_CLIENT_SECRET}} # optional
          # Google OAuth2 refresh token
          refresh-token: ${{secrets.CWS_REFRESH_TOKEN}} # optional
      # If job finished successfully, remove the workflow file (and tag if necessary)
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }}
