name: example-cron-action
'on':
  schedule:
    - cron: 0 */6 * * *
jobs:
  retryTesterCwdDeploy:
    env:
      DEV_EXTENSION_ID: dkclpenpaealjpjmgjfgcbjejobimjnj
      CLIENT_ID: 990187593175-iurgn499pfh1urue4smreg0ato5fftee.apps.googleusercontent.com
      DELAYED_JOB_CHECKOUT_REF: 033f96c006b4dd6bcd2161ceb9db6a78a45f3874
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/retryTesterCdCwd-033f96c006b4dd6bcd2161ceb9db6a78a45f3874.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
    runs-on: ubuntu-latest
    steps:
      - name: Remove scheduled job after 10 attempts
        uses: cardinalby/unschedule-job-action@v1
        if: github.run_number > 10
        with:
          ghToken: '${{ secrets.WORKFLOWS_TOKEN }}'
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - uses: actions/setup-node@v1
        with:
          node-version: 15.4
      - run: npm ci
      - run: npm run build-prod
      - name: Chrome Addon Action
        continue-on-error: true
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: '${{env.DEV_EXTENSION_ID}}'
          zip: dist/threadhelper.zip
          client-id: '${{env.CLIENT_ID}}'
          client-secret: '${{secrets.CWS_CLIENT_SECRET}}'
          refresh-token: '${{secrets.CWS_REFRESH_TOKEN}}'
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.WORKFLOWS_TOKEN }}'
